name: build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: mingw64, arch: x86_64 }
        ]
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-${{ matrix.arch }}-gcc
          make
          libtool
          autoconf
          automake-wrapper
          mingw-w64-${{ matrix.arch }}-libzip
          mingw-w64-${{ matrix.arch }}-github-cli

    - uses: actions/checkout@v4
    - name: prepare environment
      run: |
        echo "target_triplet=gcc -dumpmachine" >> $GITHUB_ENV
        git config --global core.autocrlf false

    - name: build projects
      run: |
        repos=("libplist" "libtatsu" "libimobiledevice-glue" "libusbmuxd" "libimobiledevice" "libirecovery" "idevicerestore")
        mkdir -p out
        export DESTDIR="$PWD/out"

        for repo in "${repos[@]}"; do
            echo "Building $repo..."
            git clone --depth=1 "https://github.com/libimobiledevice/$repo"
            pushd "$repo" > /dev/null
            ./autogen.sh
            make -j
            make install
            popd > /dev/null
        done


    - name: prepare release
      run: |
        tar -C out/usr/bin -cJvf libimobile-suite-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz .

    - name: publish release
      env:
        github_token: ${{secrets.GITHUB_TOKEN}}
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"
        gh release upload "$TAG" libimobile-suite-latest_${{ matrix.arch }}-${{ matrix.msystem }}.tar.xz
